version: '3.8'

services:
  userservice:
    build: ./UserProfileService/userprofile
    ports:
      - "5000:5000"
    networks:
      - app-network

  inventoryservice:
    build: ./inventory
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - userservice

  cartservice:
    build:
      context: ./CartBookService
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - userservice
      - inventoryservice

networks:
  app-network:
    driver: bridge
